version: '3.8'

services:
  db:
    container_name: learnit_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: learnit
      POSTGRES_USER: learnit
      POSTGRES_PASSWORD: learnit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U learnit"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 